linters:
  enable:
  - gosimple
  - errcheck
  - staticcheck
  - ineffassign
  - typecheck
  - govet
  - unused
  - goimports
  - prealloc
  - unconvert
  - misspell
  - whitespace
  - nakedret
  - dogsled
  - copyloopvar
